# Generated by Django 4.0.4 on 2022-06-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cook', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
